modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "vc"
version = "${version}"
displayName = "Valkyrien Computers"
authors = ["TechTastic"]
description = '''
Computer-based Mod Integration with Valkyrien Skies addons
'''
logoFile = "icon.png"

[[dependencies.vc]]
modId = "forge"
mandatory = false
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc]]
modId = "computercraft"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vc]]
modId = "valkyrienskies"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vc]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc]]
modId = "minecraft"
mandatory = false
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vc]]
modId = "architectury"
mandatory = false
versionRange = "[1.31.61,)"
ordering = "AFTER"
side = "BOTH"
